kind: pipeline
name: android-kernel-ci

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: ubuntu:latest
    # environment:
    #   AKCI_CCACHE: 1
    commands:
      - . ./print-vars.sh || exit "$?"
      - . ./prepare.sh || exit "$?"
      - ./build.sh "${AKCI_LABEL}" "${AKCI_REF}" || exit "$?"
  - name: publish
    image: plugins/github-release
    when:
      event:
        - tag
    settings:
      api_key:
        from_secret: github_token
      files: "*.zip"