kind: pipeline
name: android-kernel-ci

platform:
  os: linux
  arch: amd64

steps:
  - name: build-deps
    image: alpine:3.10
    commands:
      - apk add bash git
      - ./build-deps.sh

  - name: build
    image: ubuntu:18.04
    # environment:
    #   AKCI_CCACHE: 1
    commands:
      - apt update > /dev/null
      # required
      - apt install -y git build-essential ccache curl zip > /dev/null
      # per kernel
      - apt install -y libssl-dev bc python > /dev/null
      - ./print-vars.sh
      - ./build.sh "${AKCI_LABEL}" "${AKCI_REF}"

  - name: publish
    image: plugins/github-release
    when:
      event:
        - tag
    settings:
      api_key:
        from_secret: github_token
      files: "*.zip"